base: ./
site:
  name: NanoFX Example
  favicon: res/icon.ico
  headericon: res/icon.png
  copyright: Copyright © 2021 Crestruction.
resources:
  audiosources:
    - id: audio-nya
      title: NyaNya
      path: res/audio/nya
  stylesheets:
    - res/src/css/nanofx.css
  #javascripts:
  #  - res/src/js/nanofx.js
styles:
  section:
    - my-nanofx-block
  header:
    - my-nanofx-header
  button:
    - my-nanofx-button