base: D:/Workspace/GitLab/nanofx/src
site:
  name: NanoFX Example
  favicon: res/icon.ico
  headericon: res/icon.png
  copyright: Copyright © 2021 Crestruction.
resources:
  audiosources: 
    - res/audio/Anti
    - res/audio/Nya
  stylesheets: 
    - res/css/material.min.css
    - res/css/nanofx.css
  javascripts: 
    - res/js/material.min.js
styles:
  page:
    - nanofx-page
  section:
    - nanofx-block 
    - mdl-card 
    - mdl-shadow--2dp
  header: 
    - nanofx-header
  button: 
    - mdl-button 
    - mdl-js-button 
    - mdl-button--raised 
    - mdl-js-ripple-effect 
    - nanofx-button
